#! /bin/bash
#
# git-auto

GIT_AUTO_ROOT=$(readlink -f "${BASH_SOURCE[0]}" | xargs dirname)

source "${GIT_AUTO_ROOT}/lib/swiss.sh/swiss.sh"

main() {
  # delegate arguments to the proper command script.
  # globals:
  #   GIT_AUTO_ROOT
  # arguments:
  #   $1: git auto command to be run
  # returns:
  #   none
  local command="${1}"
  local command_path="${GIT_AUTO_ROOT}/command/${1}"
  if [[ ! -f "${command_path}" ]]; then
    usage
    exit 1
  fi
  source "${command_path}"
  ${command}_main "${@:2}"
}

usage() {
  # print out the usage instructions for git auto.
  # globals:
  #   none
  # arguments:
  #   none
  # returns:
  #   none
  echo "usage: git auto <command>"
  echo ""
  echo "where available options for <command> are:"
  echo "  feature: start, finish, or publish feature branch"
  echo "  init:    initialize repository to be compatible with git auto"
  echo "  patch:   start, finish, or publish patch on existing release"
  echo "  test:    run or show status of tests"
  echo "  version: manually manage release versions"
  echo ""
  echo "for more command details run 'git auto <command>'"
}

main "${@}"
