#! /bin/sh

## settings
set -e


## functions
#
bump_version() {
  release=$(git tag -l | grep "[0-9]\+\.[0-9]\+\.[0-9]\+" | tail -n 1)
  major=$(echo $release | sed -n "s/^\([0-9]\+\)\..*/\1/p")
  minor=$(echo $release | sed -n "s/.*\.\([0-9]\+\)\..*/\1/p")

  # increment correct version number
  case $1 in
    major) version="$(($major + 1)).0.0"      ;;
    minor) version="$major.$(($minor + 1)).0" ;;
    *)     usage                              ;;
  esac

  # add new tag to current release
  git checkout -q release
  git tag -a $version
}


#
usage() {
  echo -e "usage: git auto version <command> <arg>"
  echo -e "\nwhere available options for <command> are:"
  echo -e "  bump\tincrement version number where <arg> is major or minor"
  echo -e "\nfor more command details run 'git auto <command> help'"
  exit 1
}


## main
# parse command line options
option=$1
shift
case $option in
  bump) bump_version $@ ;;
  *)    usage           ;;
esac
