#! /bin/sh

# version_bump increments the specified part of the version number by one
#   $1  the part of the version number to increment (major, minor, build)
version_bump() {
  major=$(get_latest_release major)
  minor=$(get_latest_release minor)
  build=$(get_latest_release build)

  # increment correct version number
  case "$1" in
    major)
      version="$(($major + 1)).0.0" ;;
    minor)
      version="$major.$(($minor + 1)).0" ;;
    build)
      version="$major.$minor.$(($build + 1))" ;;
    *)
      version_usage
      exit 1 ;;
  esac

  # add new tag to current release
  git checkout -q release
  git tag -a $version
}


# version_usage prints the usage instructions for the version subcommand
version_usage() {
  log_info "usage: git auto version <command> <arg>"
  log_info ""
  log_info "where available options for <command> are:"
  log_info "  bump  increment version number where <arg> is major or minor"
  log_info ""
  log_info "for more command details run 'git auto <command> help'"
}


#
version_main() {
  option=$1
  shift
  case $option in
    bump)
      version_bump $@ ;;
    *)
      version_usage
      exit 1 ;;
  esac
}
