#!/bin/bash
#
# TODO(mraxilus): document header

if [[ "$(git rev-parse --abbrev-ref HEAD)" != "master" ]]; then
  exit 0
fi
# TODO(mraxilus): verify tests before merge
echo "automated testing unimplimented"
git auto release
git auto prune
