#!/bin/bash
#
# TODO(mraxilus): document header

if [[ "$(git rev-parse --abbrev-ref HEAD)" != "master" ]]; then
  exit 0
fi
# TODO(mraxilus): verify tests before merge
echo "automated testing unimplimented"
# TODO(mraxilus): fail safely
git checkout release
git merge master --no-ff --strategy-option=theirs
major="$(git auto version show major)"
minor="$(git auto version show minor)"
build="$(git auto version show build)"
git tag -a "$major.$minor.$(($build + 1))" -m "automatic increment"
git checkout master
