#!/bin/bash
#
# TODO(mraxilus): document header

feature_finish() {
  # TODO(mraxilus): document feature_finish
  if [[ ${#} < 1 ]]; then
    feature_usage
    exit 1
  fi
  local branch="feature/$1"
  git checkout master
  git merge --no-ff "$branch"
  git branch -d "$branch"
}

#
feature_publish() {
  # TODO(mraxilus}: implement feature publishing
  echo "feature_publish unimplemented"
}

#
feature_start() {
  # TODO(mraxilus): document feature_start
  git checkout -b "feature/${1}" master
}

#
feature_usage() {
  # TODO(mraxilus): document feature_usage
  echo "usage: git auto feature <command> <arg>"
  echo ""
  echo "where available options for <command> are:"
  echo "  finish:  merge feature branch named <arg> into master and delete it"
  echo "  publish: push feature branch named <arg> to origin"
  echo "  start:   create new feature branch named <arg>"
  echo ""
  echo "for more command details run 'git auto <command>'"
}

feature_main() {
  # TODO(mraxilus): document feature_main
  if ! declare -f -F "feature_${1}" > /dev/null; then
    feature_usage
    exit 1
  fi
  feature_${1} "${@:2}"
}
