#! /bin/bash
#
# init

init_main() {
  # initialize a git auto repository by setting up files, tags, and hooks
  # globals:
  #   GIT_AUTO_ROOT
  # arguments:
  #   none
  # returns:
  #   none
  git init 
  if ! git rev-parse HEAD &> /dev/null; then
    touch git-auto.yaml
    git add git-auto.yaml
    git commit -m "initialize repository"

    # create branch for releases
    git checkout -b release master
    git tag -a "0.0.0" -m "initialize automatic versioning"
    git checkout master
  fi

  # install git hooks
  for hook in "${GIT_AUTO_ROOT}/hook/*"; do
    rsync ${GIT_AUTO_ROOT}/hook/* .git/hooks
  done
}
