#! /bin/sh

init_main() {
  # initialize repository
  git init 
  touch git-auto.yaml
  git add git-auto.yaml
  git commit -m "incept repository"

  # create branch for releases
  git checkout -b release master
  git tag -a 0.0.0 -m "incept release versioning"
  git checkout master
}
