#! /bin/bash
#
# TODO(mraxilus): document header

init_main() {
  # TODO(mraxilus): document main
  # initialize repository
  git init 
  touch git-auto.yaml
  git add git-auto.yaml
  git commit -m "initialize repository"

  # create branch for releases
  git checkout -b release master
  git tag -a "0.0.0" -m "initialize automatic versioning"
  git checkout master

  # install git hooks
  for hook in "${GIT_AUTO_ROOT}/hook/*"; do
    rsync ${GIT_AUTO_ROOT}/hook/* .git/hooks
  done
}
