#! /bin/bash
# this file is part of git-auto which is released under the mit license.
# go to http://opensource.org/licenses/mit for full details.

release_main() {
  # create a new release from master branch, incrementing build number
  # globals:
  #   none
  # arguments:
  #   none
  # returns:
  #   none
  git checkout release
  git merge master --no-ff --strategy-option=theirs -m "create release"
  major="$(git auto version show major)"
  minor="$(git auto version show minor)"
  build="$(git auto version show build)"
  git tag --annotate "$major.$minor.$(($build + 1))" \
    --message="increment build number"
  git checkout master
}
