#!/bin/bash
#
# post-commit

# get_latest_version outputs the latest version tag on the release branch
#   $1  get a particular part of the version number (major, minor, build)
get_version() {
  release=$(git tag -l | grep "[0-9]\+\.[0-9]\+\.[0-9]\+" | tail -n 1)
  case "$1" in
    build) echo $(echo $release | sed -n "s/.*\.\([0-9]\+\)$/\1/p")    ;;
    major) echo $(echo $release | sed -n "s/^\([0-9]\+\)\..*/\1/p")    ;;
    minor) echo $(echo $release | sed -n "s/.*\.\([0-9]\+\)\..*/\1/p") ;;
    *)     echo $release                                               ;;
  esac
}

if [[ "$(git rev-parse --abbrev-ref HEAD)" != "master" ]]; then
  exit 0
fi

# TODO(mraxilus): verify tests before merge
git checkout release
git merge master --no-ff --strategy-option=theirs
major=$(get_version major)
minor=$(get_version minor)
build=$(get_version build)
git tag -a "$major.$minor.$(($build + 1))" -m "increment build automatically"
git checkout master
    
