#! /bin/bash
# this file is part of git-auto which is released under the mit license.
# go to http://opensource.org/licenses/mit for full details.

init_main() {
  # initialize a git auto repository by setting up files, tags, and hooks
  # globals:
  #   GIT_AUTO_ROOT
  # arguments:
  #   none
  # returns:
  #   none
  git init 
  # initialize repository if new or no initial version exists.
  if ! git rev-parse HEAD &> /dev/null ||\
     ! git tag -l | grep 0.0.0 &> /dev/null; then 
    git checkout master || true
    git commit --allow-empty --message="initialize repository with git auto"
    git tag -a "0.0.0" -m "prepare for automatic versioning"
    git push --set-upstream origin master --follow-tags
    git checkout -b release master
    git push --set-upstream origin release --follow-tags
  fi

  # install git hooks
  for hook in "${GIT_AUTO_ROOT}/hook/*"; do
    rsync ${hook} .git/hooks
  done
}
