#! /bin/bash
# this file is part of git-auto which is released under the mit license.
# go to http://opensource.org/licenses/mit for full details.

prune_main() {
  # remove all merged local and remote branches which aren't release or master.
  # globals:
  #   none
  # arguments:
  #   none
  # returns:
  #   none
  git branch --no-color --merged \
    | grep -v "master" \
    | xargs git branch -d
  git branch --no-color -r --merged \
    | grep -v "master\|release" \
    | sed -r "s:^.*origin/::g" \
    | xargs -I branch git push origin :branch
}
