#!/bin/bash
#
# test

test_main() {
  # delegate arguments to the proper test function
  # globals:
  #   none
  # arguments:
  #   $1: name of the test function excluding the preceeding "test_"
  # returns:
  #   none
  if ! declare -f -F "test_${1}" > /dev/null; then
    test_usage
    exit 1
  fi
  test_${1} "${@:2}"
}

test_run() {
  # run tests on current commit
  # globals:
  #   none
  # arguments:
  #   $@: names of tests to run on current commit
  # returns:
  #   none
  echo "test_run unimplemented"
}

test_show() {
  # show details of test statuses
  # globals:
  #   none
  # arguments:
  #   $@: names of tests to show status details for
  # returns:
  #   none
  echo "test_show unimplemented"
}

test_usage() {
  # print out the usage instructions for git auto test
  # globals:
  #   none
  # arguments:
  #   none
  # returns:
  #   none
  echo "usage: git auto test <command> [<arg>]"
  echo ""
  echo "where available options for <command> are:"
  echo "  run:  run test(s) [<arg>] on current commit (default run all)"
  echo "  show: show status of test(s) [<arg>] (default show all)"
  echo ""
  echo "for more command details run 'git auto <command>'"
}
